# staticman comments configuration
staticman_url: https://staticman-commentaires.herokuapp.com/v3/entry/github/poilssurlesseins/poilssurlesseins/main

# _config.yml (defaults)
repository  : "Poilssurlesseins/poilssurlesseins.github.io"
comments:
  provider  : "staticman_v2"
  staticman:
    branch    : "main"
    endpoint  : https://staticman-commentaires.herokuapp.com/v3/entry/github/